# -*- coding: utf-8 -*-
"""PythonTask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dwFSGBicXt-7ioMwFwd5s7E77YTb9rZf

#Import
"""

import pandas as pd

"""# Tasks

## 1- Read the table from CSV
"""

table = pd.read_csv("/content/Employees.csv")
print(table.info())
table.head(9)

"""## 2- Remove duplicates"""

table.drop_duplicates(inplace = True)
print(table.info())
table.head(9)

"""## 3- Remove any decimal point in the age coloumn"""

table["Age"] = (round(table[["Age"]]))
print(table.info())
table.head(9)

"""## 4- convert the USD salary to EGP"""

table["salary(EGP)"] = table["Salary(USD)"]*30
print(table.info())
table.head(9)

"""## 4- print some stats (AVG age, Median Salaries, Ration "Males/Females", ...)"""

avg_age = table["Age"].mean()
med_salary = table["salary(EGP)"].median()
num_gender = table["Gender"].value_counts()
t=num_gender["F"]
s=num_gender["M"]
ratio=s/t
print(avg_age,med_salary,num_gender,ratio)

"""## 5- Save the edited table to a CSV file"""

table.to_csv("/content/newEmployees.csv")

"""# END"""